name: Auto Fill PR Template

on:
    pull_request:
        types: [opened]

jobs:
    fill-pr-template:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Check if PR title already contains template
              id: check_pr_title
              run: |
                  echo "title=$(gh pr view ${{ github.event.number }} --json title --jq .title)" >> $GITHUB_ENV
                  echo "body=$(gh pr view ${{ github.event.number }} --json body --jq .body)" >> $GITHUB_ENV

            - name: Fill PR Template
              if: env.title == '' || env.body == ''
              uses: repo-sync/pull-request@v2
              with:
                  github_token: ${{ secrets.CODESANDBOX_GITHUB_TOKEN }}
                  pr_title: 'Auto-filled PR Template'
                  pr_template: '.github/pull_request_template.md'
