name: CI - Build Stage

on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.11.0]

        steps:
            - uses: actions/checkout@v2

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test

            - name: Prepare build
              run: pnpm run prepublish

            - name: Determine version type and publish
              run: |
                  if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
                    pnpm run pub:patch
                    echo "Publishing a Patch Release"
                    pnpm publish --access public
                  elif [[ $GITHUB_REF == 'refs/heads/master' ]]; then
                    pnpm run pub:beta
                    echo "Publishing a Beta Release"
                    pnpm publish --tag beta --access public
                  fi
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
