name: CI - Build Stage

on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test

            - name: Prepare build
              run: pnpm run prepublish

            - name: Configure Git identity
              run: |
                  git config --local user.email "fengwenxuan2006@126.com"
                  git config --local user.name "wenxuan"

            - name: Publish to npm
              run: |
                  pnpm publish --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
