name: CI - Build Stage

on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test

            - name: Prepare build
              run: pnpm run prepublish

            - name: Configure Git identity
              run: |
                  git config --local user.email "fengwenxuan2006@126.com"
                  git config --local user.name "wenxuan"

            - name: Update version and commit
              run: |
                  NEW_VERSION=$(pnpm run pub:beta | grep -oP '(?<=\+).*(?=\s)')
                  git add package.json
                  git commit -m "chore: bump version to $NEW_VERSION"
                  git push
                  echo "Publishing a Beta Release"
                  pnpm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
